[package]
name = "xenon3"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
flate2 = "1.0.34"
inotify = "0.11.0"
libc = "0.2.161"
log = "0.4.22"
rhai = "1.19.0"
signal-hook = "0.3.17"
simplelog = "0.12.2"
